List<Map<String, dynamic>> mediaData = [
  // Entry 1-20
  {
    "title": "Inception",
    "type": "Film",
    "description": "A skilled thief, the absolute best in the dangerous art of extraction, stealing valuable secrets from deep within the subconscious during the dream state.",
    "rating": 8.8,
    "releaseDate": "2010-07-16",
    "image": "https://upload.wikimedia.org/wikipedia/ar/e/e8/%D8%BA%D9%84%D8%A7%D9%81_%D9%81%D9%84%D9%85_%D8%A7%D8%B3%D8%AA%D9%87%D9%84%D8%A7%D9%84_%282010%29.jpeg",
    "video": "https://www.youtube.com/watch?v=YoHD9XEInc0",
    "genre": ["Sci-Fi", "Action"],
    "cast": ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Ellen Page"],
    "director": "Christopher Nolan",
    "duration": "2h 28m",
    "ageRating": "PG-13"
  },
  {
    "title": "Breaking Bad",
    "type": "Series",
    "description": "A high school chemistry teacher turned methamphetamine producer faces challenges in his dangerous new career.",
    "rating": 9.5,
    "releaseDate": "2008-01-20",
    "image":"https://m.media-amazon.com/images/M/MV5BMzU5ZGYzNmQtMTdhYy00OGRiLTg0NmQtYjVjNzliZTg1ZGE4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    "video": "https://www.youtube.com/watch?v=HhesaQXLuRY",
    "genre": ["Crime", "Drama", "Thriller"],
    "cast": ["Bryan Cranston", "Aaron Paul", "Anna Gunn"],
    "director": "Vince Gilligan",
    "duration": "5 Seasons",
    "ageRating": "TV-MA"
  },
  // Add additional entries in a similar format.
  {
    "title": "Parasite",
    "type": "Film",
    "description": "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    "rating": 8.6,
    "releaseDate": "2019-05-30",
    "image": "https://i.ytimg.com/vi/isOGD_7hNIY/sddefault.jpg",
    "video": "https://www.youtube.com/watch?v=5xH0HfJHsaY",
    "genre": ["Thriller", "Drama"],
    "cast": ["Kang-ho Song", "Sun-kyun Lee", "Yeo-jeong Jo"],
    "director": "Bong Joon Ho",
    "duration": "2h 12m",
    "ageRating": "R"
  },
  {
    "title": "The Crown",
    "type": "Series",
    "description": "A drama that chronicles the life of Queen Elizabeth II from the 1940s to modern times.",
    "rating": 8.7,
    "releaseDate": "2016-11-04",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtQyTSGoBOHXR_A6CHP60yJ00Ln_SVtgu5QFCM5fnbvTx34pq1_JSzt6gQjoCM6DfKUqbEb8PSDOAewHMqoRplYipQ7A556J2n23vGwg",
    "video": "https://www.youtube.com/watch?v=JWtnJjn6ng0",
    "genre": ["Drama", "History"],
    "cast": ["Claire Foy", "Olivia Colman", "Matt Smith"],
    "director": "Peter Morgan",
    "duration": "6 Seasons",
    "ageRating": "TV-MA"
  },
  {
    "title": "Squid Game",
    "type": "Series",
    "description": "Hundreds of cash-strapped players accept a strange invitation to compete in children's games with high stakes and deadly consequences.",
    "rating": 8.1,
    "releaseDate": "2021-09-17",
    "image": "https://asianwiki.com/images/0/0e/Squid_Game-p2.jpg",
    "video": "https://www.youtube.com/watch?v=oqxAJKy0ii4",
    "genre": ["Drama", "Thriller"],
    "cast": ["Lee Jung-jae", "Park Hae-soo", "Jung Ho-yeon"],
    "director": "Hwang Dong-hyuk",
    "duration": "1 Season",
    "ageRating": "TV-MA"
  },
  {
    "title": "Interstellar",
    "type": "Film",
    "description": "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    "rating": 8.6,
    "releaseDate": "2014-11-07",
    "image": "https://i.ytimg.com/vi/YF1eYbfbH5k/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGE4gYShlMA8=&rs=AOn4CLDt6JPoesvmQnP8qf-00JpeDZUfyA",
    "video": "https://www.youtube.com/watch?v=zSWdZVtXT7E",
    "genre": ["Adventure", "Drama", "Sci-Fi"],
    "cast": ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    "director": "Christopher Nolan",
    "duration": "2h 49m",
    "ageRating": "PG-13"
  },
  {
    "title": "Stranger Things",
    "type": "Series",
    "description": "A group of young friends in a small town uncover a series of supernatural mysteries involving secret experiments and otherworldly creatures.",
    "rating": 8.7,
    "releaseDate": "2016-07-15",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZElSFrw1uQpmghSqjfiazrAYooapH75STyFOVHvdva5sGKpAgLVF4wPPkS8Iu1aD3PlJ4-C7apM2cexpahrE16yQSzLB864tWFqfbw6U",
    "video": "https://www.youtube.com/watch?v=b9EkMc79ZSU",
    "genre": ["Drama", "Fantasy", "Horror"],
    "cast": ["Millie Bobby Brown", "Finn Wolfhard", "Winona Ryder"],
    "director": "The Duffer Brothers",
    "duration": "4 Seasons",
    "ageRating": "TV-14"
  },
  {
    "title": "Game of Thrones",
    "type": "Series",
    "description": "Nine noble families wage war against each other to gain control over the mythical land of Westeros.",
    "rating": 9.2,
    "releaseDate": "2011-04-17",
    "image": "https://static.hbo.com/game-of-thrones-1-1920x1080.jpg",
    "video": "https://www.youtube.com/watch?v=gcTkNV5Vg1E",
    "genre": ["Action", "Drama", "Fantasy"],
    "cast": ["Emilia Clarke", "Peter Dinklage", "Kit Harington"],
    "director": "David Benioff, D.B. Weiss",
    "duration": "8 Seasons",
    "ageRating": "TV-MA"
  },
  {
    "title": "The Mandalorian",
    "type": "Series",
    "description": "A lone bounty hunter in the outer reaches of the galaxy protects a mysterious child.",
    "rating": 8.7,
    "releaseDate": "2019-11-12",
    "image": "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcRkKeBet-9ip4vgVBAGJ9S3FwlZ6KdHsd1UvRwfcuQ4bud8UZQ5ObYL5t9OFqJXMKo9blDdBzW-LCwtOpEoHRg_ws_uCSKWdBiI2l87Ag",
    "video": "https://www.youtube.com/watch?v=aOC8E8z_ifw",
    "genre": ["Action", "Adventure", "Sci-Fi"],
    "cast": ["Pedro Pascal", "Gina Carano", "Carl Weathers"],
    "director": "Jon Favreau",
    "duration": "3 Seasons",
    "ageRating": "TV-14"
  },
  {
    "title": "The Matrix",
    "type": "Film",
    "description": "A hacker discovers the truth about his reality and his role in the war against its controllers.",
    "rating": 8.7,
    "releaseDate": "1999-03-31",
    "image": "https://upload.wikimedia.org/wikipedia/ar/c/c1/The_Matrix_Poster.jpg",
    "video": "https://www.youtube.com/watch?v=m8e-FF8MsqU",
    "genre": ["Action", "Sci-Fi"],
    "cast": ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
    "director": "The Wachowskis",
    "duration": "2h 16m",
    "ageRating": "R"
  },
  {
    "title": "Avatar: The Way of Water",
    "type": "Film",
    "description": "Jake Sully and Neytiri navigate life as parents on Pandora while facing new threats.",
    "rating": 7.8,
    "releaseDate": "2022-12-16",
    "image": "https://i.ytimg.com/vi/d9MyW72ELq0/maxresdefault.jpg",
    "video": "https://www.youtube.com/watch?v=d9MyW72ELq0",
    "genre": ["Action", "Adventure", "Sci-Fi"],
    "cast": ["Sam Worthington", "Zoe Saldana", "Sigourney Weaver"],
    "director": "James Cameron",
    "duration": "3h 12m",
    "ageRating": "PG-13"
  },
  {
    "title": "Money Heist",
    "type": "Series",
    "description": "A criminal mastermind plans the biggest heist in history, targeting the Royal Mint of Spain.",
    "rating": 8.2,
    "releaseDate": "2017-05-02",
    "image": "https://resizing.flixster.com/ITt1FPrFePNR6FSqZrZK7BocG2U=/ems.cHJkLWVtcy1hc3NldHMvdHZzZWFzb24vUlRUVjEwMTMyOTMud2VicA==",
    "video": "https://www.youtube.com/watch?v=_InqQJRqGW4",
    "genre": ["Action", "Crime", "Drama"],
    "cast": ["Úrsula Corberó", "Álvaro Morte", "Itziar Ituño"],
    "director": "Álex Pina",
    "duration": "5 Seasons",
    "ageRating": "TV-MA"
  },
  {
    "title": "The Office",
    "type": "Series",
    "description": "A mockumentary on a group of typical office workers in a dysfunctional company.",
    "rating": 8.9,
    "releaseDate": "2005-03-24",
    "image": "https://m.media-amazon.com/images/I/81NK3yCvMJL._AC_UF894,1000_QL80_.jpg",
    "video": "https://www.youtube.com/watch?v=BJpG5ZHBOxA",
    "genre": ["Comedy"],
    "cast": ["Steve Carell", "Rainn Wilson", "Jenna Fischer"],
    "director": "Greg Daniels",
    "duration": "9 Seasons",
    "ageRating": "TV-PG"
  },
  {
    "title": "Spider-Man: No Way Home",
    "type": "Film",
    "description": "Peter Parker's identity is revealed, bringing his superhero responsibilities into conflict with his normal life.",
    "rating": 8.3,
    "releaseDate": "2021-12-17",
    "image": "https://upload.wikimedia.org/wikipedia/en/0/00/Spider-Man_No_Way_Home_poster.jpg",
    "video": "https://www.youtube.com/watch?v=JfVOs4VSpmA",
    "genre": ["Action", "Adventure", "Sci-Fi"],
    "cast": ["Tom Holland", "Zendaya", "Benedict Cumberbatch"],
    "director": "Jon Watts",
    "duration": "2h 28m",
    "ageRating": "PG-13"
  },
  {
    "title": "Black Panther",
    "type": "Film",
    "description": "T'Challa returns home to Wakanda to take his rightful place as king, but a powerful enemy reemerges.",
    "rating": 7.3,
    "releaseDate": "2018-02-16",
    "image": "https://upload.wikimedia.org/wikipedia/en/9/9f/Black_Panther_OS_Vol_1_2.png",
    "video": "https://www.youtube.com/watch?v=xjDjIWPwcPU",
    "genre": ["Action", "Adventure", "Sci-Fi"],
    "cast": ["Chadwick Boseman", "Michael B. Jordan", "Lupita Nyong'o"],
    "director": "Ryan Coogler",
    "duration": "2h 14m",
    "ageRating": "PG-13"
  },
  {
    "title": "The Boys",
    "type": "Series",
    "description": "A group of vigilantes sets out to take down corrupt superheroes who abuse their powers.",
    "rating": 8.7,
    "releaseDate": "2019-07-26",
    "image": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRIQhi6OBCVVEZdpaj3vrCkuUtI6PcGmM6XoR2TQ1pszU4aT_ArAWqOE-auOBEXvVzBrx1eOp_Ie5iiUhZPX7BVSRYI-P95tvTyOF8JSw",
    "video": "https://www.youtube.com/watch?v=06rueu_fh30",
    "genre": ["Action", "Comedy", "Crime"],
    "cast": ["Karl Urban", "Jack Quaid", "Antony Starr"],
    "director": "Eric Kripke",
    "duration": "3 Seasons",
    "ageRating": "TV-MA"
  },
   {
    "title": "Spider-Man: No Way Home",
    "type": "Film",
    "description": "Peter Parker's identity is revealed, and he enlists the help of Doctor Strange. Things go awry, leading to the multiverse unraveling.",
    "rating": 8.3,
    "releaseDate": "2021-12-17",
    "image": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcScdztrbZdxN9P1Ztzap_56b_kXhZMO2P7nLDbS5SnUP5JNV1LU4pqH1hhW7zwTbn0GeM1ifTzu8Cq3ey9V2uFD2B2xJGVncoT0bP1UUw",
    "video": "https://www.youtube.com/watch?v=JfVOs4VSpmA",
    "genre": ["Action", "Adventure", "Sci-Fi"],
    "cast": ["Tom Holland", "Zendaya", "Benedict Cumberbatch"],
    "director": "Jon Watts",
    "duration": "2h 28m",
    "ageRating": "PG-13"
  },
  {
    "title": "Friends",
    "type": "Series",
    "description": "Follows the lives of six 20-something friends living in New York City as they navigate love, career, and friendship.",
    "rating": 8.9,
    "releaseDate": "1994-09-22",
    "image": "https://play-images-prod-ctf.tech.tvnz.co.nz/api/v1/web/image/3CLEzO37tocxCoSmzzcxwx/2733ae58689b3e59e477a86d2da48a36/friends-showtile.png.2733ae58689b3e59e477a86d2da48a36.jpg?width=1200&height=630",
    "video": "https://www.youtube.com/watch?v=hDNNmeeJs1Q",
    "genre": ["Comedy", "Romance"],
    "cast": ["Jennifer Aniston", "Courteney Cox", "Matthew Perry"],
    "director": "David Crane, Marta Kauffman",
    "duration": "10 Seasons",
    "ageRating": "TV-14"
  },
  {
    "title": "Avengers: Endgame",
    "type": "Film",
    "description": "After the devastating events of Infinity War, the Avengers assemble one last time to undo the actions of Thanos.",
    "rating": 8.4,
    "releaseDate": "2019-04-26",
    "image": "https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/DB176BD1488D7E4822256EF1778C124FC17388FC1E7F0F6D89B38AFF5FB001F6/scale?width=1200&aspectRatio=1.78&format=webp",
    "video": "https://www.youtube.com/watch?v=TcMBFSGVi1c",
    "genre": ["Action", "Adventure", "Drama"],
    "cast": ["Robert Downey Jr.", "Chris Evans", "Scarlett Johansson"],
    "director": "Anthony Russo, Joe Russo",
    "duration": "3h 1m",
    "ageRating": "PG-13"
  },
  {
    "title": "Sherlock",
    "type": "Series",
    "description": "A modern update to the stories of Sherlock Holmes, solving mysteries in 21st-century London.",
    "rating": 9.1,
    "releaseDate": "2010-07-25",
    "image": "https://m.media-amazon.com/images/M/MV5BNTQzNGZjNDEtOTMwYi00MzFjLWE2ZTYtYzYxYzMwMjZkZDc5XkEyXkFqcGc@._V1_QL75_UX190_CR0,2,190,281_.jpg",
    "video": "https://www.youtube.com/watch?v=qlcWFoNqZHc",
    "genre": ["Crime", "Drama", "Mystery"],
    "cast": ["Benedict Cumberbatch", "Martin Freeman", "Una Stubbs"],
    "director": "Steven Moffat, Mark Gatiss",
    "duration": "4 Seasons",
    "ageRating": "TV-14"
  },
  {
    "title": "The Lord of the Rings: The Fellowship of the Ring",
    "type": "Film",
    "description": "A young hobbit and his friends set out on a dangerous journey to destroy the One Ring.",
    "rating": 8.8,
    "releaseDate": "2001-12-19",
    "image": "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1654215925i/61215351.jpg",
    "video": "https://www.youtube.com/watch?v=V75dMMIW2B4",
    "genre": ["Action", "Adventure", "Drama"],
    "cast": ["Elijah Wood", "Ian McKellen", "Viggo Mortensen"],
    "director": "Peter Jackson",
    "duration": "3h 48m",
    "ageRating": "PG-13"
  },
  {
    "title": "House of the Dragon",
    "type": "Series",
    "description": "A prequel to Game of Thrones, detailing the history of House Targaryen.",
    "rating": 8.4,
    "releaseDate": "2022-08-21",
    "image": "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcRqRvfxRETljBjXLuSdqkKx7KoOuWQszbcQZV1A6o_N_kwL-0rNDbS8VKBicVNrHjUtiwPjhH0vJc39sgloA1lrMj4sU9eVU6OnKDDyKaU",
    "video": "https://www.youtube.com/watch?v=DotnJ7tTA34",
    "genre": ["Action", "Drama", "Fantasy"],
    "cast": ["Paddy Considine", "Emma D'Arcy", "Matt Smith"],
    "director": "Miguel Sapochnik",
    "duration": "1 Season",
    "ageRating": "TV-MA"
  }
  // Continue similar entries to reach a total of 60.
];
List<Map<String, dynamic>> mediaDataReversed = mediaData.reversed.toList();
